import { getTursoConnection } from '@/lib/db/turso';
import { randomUUID } from 'node:crypto';
import type { AdminMarket } from './types';
import type { CreateMarketData,UpdateMarketData } from './repository';
function map(r:any):AdminMarket{return{id:String(r.id),name:r.name,address:r.address??'',city:r.city??'',state:r.state??'',zip:r.zip??'',lat:Number(r.latitude??0),lng:Number(r.longitude??0),hours:r.hours??'',dayOfWeek:Number(r.day_of_week??0),description:r.description??'',mapsUrl:r.maps_url??'',isActive:Boolean(r.active),featured:Boolean(r.featured),createdAt:r.created_at??new Date(0).toISOString(),updatedAt:r.updated_at??new Date(0).toISOString()}}
const select='SELECT id,name,address,city,state,zip,latitude,longitude,hours,day_of_week,description,maps_url,active,featured,created_at,updated_at FROM markets';
export async function listTursoMarkets(activeOnly=false){return(await getTursoConnection().all(`${select}${activeOnly?' WHERE active = 1':''} ORDER BY name`)).map(map)}
export async function getTursoMarketById(id:string){const value=await getTursoConnection().get(`${select} WHERE id = ? LIMIT 1`,id);return value?map(value):null}
export async function createTursoMarket(data:CreateMarketData){const id=randomUUID(),now=new Date().toISOString();await getTursoConnection().run(`INSERT INTO markets(id,name,address,city,state,zip,latitude,longitude,hours,day_of_week,description,maps_url,featured,active,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,id,data.name,data.address,data.city,data.state,data.zip,data.lat,data.lng,data.hours,data.dayOfWeek,data.description,data.mapsUrl??'',data.featured?1:0,data.isActive===false?0:1,now,now);return getTursoMarketById(id) as Promise<AdminMarket>}
export async function updateTursoMarket(id:string,data:UpdateMarketData){const columns:{[key:string]:string}={name:'name',address:'address',city:'city',state:'state',zip:'zip',lat:'latitude',lng:'longitude',hours:'hours',dayOfWeek:'day_of_week',description:'description',mapsUrl:'maps_url',isActive:'active',featured:'featured'};const sets=['updated_at=?'],values:any[]=[new Date().toISOString()];for(const [key,column] of Object.entries(columns)){const value=(data as any)[key];if(value===undefined)continue;sets.push(`${column}=?`);values.push(typeof value==='boolean'?(value?1:0):value)}const result=await getTursoConnection().run(`UPDATE markets SET ${sets.join(',')} WHERE id=?`,...values,id);return Number(result.rowsAffected)===1?getTursoMarketById(id):null}
export async function deleteTursoMarket(id:string){return Number((await getTursoConnection().run('DELETE FROM markets WHERE id=?',id)).rowsAffected)>0}
export async function seedTursoMarkets(defaults:CreateMarketData[]){const db=getTursoConnection();const count=await db.get('SELECT count(*) AS count FROM markets');if(Number(count?.count??0)>0)return{seeded:0};await db.transactionAsync(async(tx)=>{for(const value of defaults){const id=randomUUID(),now=new Date().toISOString();await tx.run(`INSERT INTO markets(id,name,address,city,state,zip,latitude,longitude,hours,day_of_week,description,maps_url,featured,active,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,id,value.name,value.address,value.city,value.state,value.zip,value.lat,value.lng,value.hours,value.dayOfWeek,value.description,value.mapsUrl??'',value.featured?1:0,value.isActive===false?0:1,now,now)}});return{seeded:defaults.length}}
