// Updated Product Catalog with accurate prices from tasteofgratitude.shop
// All prices match Square Online store as of current date

export const PRODUCTS = [
  // GELS - Premium Sea Moss Products
  {
    id: 'elderberry-moss',
    slug: 'elderberry-moss',
    name: 'Elderberry Moss',
    category: 'gel',
    price: 36.00,
    size: '16oz',
    description: 'Elderberry Moss Gels combine the natural goodness of sea moss and elderberry for a nutrient-rich addition to your daily routine. This gel is made with natural ingredients and is simple to incorporate into your wellness practice.*',
    image: 'https://127690646.cdn6.editmysite.com/uploads/1/2/7/6/127690646/CPFQJP5N2DGVL5US32BI5WFV.jpeg',
    ingredients: ['Sea Moss', 'Elderberry', 'Natural Ingredients'],
    benefits: ['May Support Immune Wellness*', 'Rich Mineral Content', 'Nutrient-Rich'],
    fdaDisclaimer: true,
    squareProductUrl: 'https://tasteofgratitude.shop/s/order?add=elderberry-moss',
    featured: true,
    inStock: false,
    rewardPoints: 36
  },
  {
    id: 'healing-harmony',
    slug: 'healing-harmony',
    name: 'Healing Harmony',
    category: 'gel',
    price: 35.00,
    size: '16oz',
    description: 'Soursop Rich in antioxidants, may support immune wellness.* Cinnamon traditionally used to support healthy blood sugar levels,* warming spice. Star Anise supports digestion, aromatic flavor. Sea Moss offers rich mineral content, traditionally used in wellness routines.* Alkaline Water hydrating, helps maintain pH balance.',
    image: 'https://127690646.cdn6.editmysite.com/uploads/1/2/7/6/127690646/ZHB653PNM4Q6HSEPML2YQRPP.jpeg',
    ingredients: ['Soursop', 'Cinnamon', 'Star Anise', 'Sea Moss', 'Alkaline Water'],
    benefits: ['May Support Immune Wellness*', 'Traditionally Warming*', 'May Support Healthy Blood Sugar*', 'Digestive Support'],
    fdaDisclaimer: true,
    squareProductUrl: 'https://tasteofgratitude.shop/s/order?add=healing-harmony',
    featured: true,
    inStock: true,
    lowStock: true,
    rewardPoints: 35
  },
  {
    id: 'golden-glow-gel',
    slug: 'golden-glow-gel',
    name: 'Golden Glow Gel',
    category: 'gel',
    price: 36.00,
    priceMini: 11.00,
    sizes: ['2oz Shot', '16oz Gel'],
    description: 'Pineapple, Orange, Turmeric, Ginger, Local Honey, Alkaline Water. Contains compounds traditionally associated with comfort,* may support wellness and digestion,* promotes radiant skin, aids recovery.*',
    image: 'https://127690646.cdn6.editmysite.com/uploads/1/2/7/6/127690646/IB23YBEFP6SBAIOEWT4L5ARY.jpeg',
    ingredients: ['Pineapple', 'Orange', 'Turmeric', 'Ginger', 'Local Honey', 'Alkaline Water'],
    benefits: ['Traditional Comfort Blend*', 'May Support Wellness*', 'Radiant Skin', 'Recovery Support*'],
    fdaDisclaimer: true,
    squareProductUrl: 'https://tasteofgratitude.shop/s/order?add=golden-glow-gel',
    featured: false,
    inStock: true,
    lowStock: true,
    rewardPoints: 36
  },
  {
    id: 'blue-lotus',
    slug: 'blue-lotus',
    name: 'Blue Lotus',
    category: 'gel',
    price: 36.00,
    priceMini: 11.00,
    sizes: ['2oz Shot', '16oz Gel'],
    description: 'Blue Spirulina, Horny Goat Weed, Ashwagandha, Maca Root, Ginger, Agave. Used in traditional wellness practices,* promotes focus & calm energy, crafted with adaptogens traditionally used for vitality.*',
    image: 'https://127690646.cdn6.editmysite.com/uploads/1/2/7/6/127690646/5ICW6ZAQAEH3PGEZBWBDXFRQ.jpeg',
    ingredients: ['Blue Spirulina', 'Horny Goat Weed', 'Ashwagandha', 'Maca Root', 'Ginger', 'Agave'],
    benefits: ['Traditional Wellness Blend*', 'Focus & Calm', 'Adaptogen Blend*', 'Vitality Support*'],
    fdaDisclaimer: true,
    squareProductUrl: 'https://tasteofgratitude.shop/s/order?add=blue-lotus',
    featured: false,
    inStock: true,
    lowStock: true,
    rewardPoints: 36
  },
  {
    id: 'grateful-greens',
    slug: 'grateful-greens',
    name: 'Grateful Greens',
    category: 'gel',
    price: 35.00,
    description: 'Holy Basil, Spirulina, Chlorophyll, Chlorella, Local Honey. Alkalizing greens, used in traditional wellness practices,* nutrient-dense blend.*',
    image: 'https://127690646.cdn6.editmysite.com/uploads/1/2/7/6/127690646/WZXG7JSUC2EYTSTJLERXRSYL.jpeg',
    ingredients: ['Holy Basil', 'Spirulina', 'Chlorophyll', 'Chlorella', 'Local Honey'],
    benefits: ['Alkalizing', 'Traditional Wellness Blend*', 'Nutrient-Dense'],
    fdaDisclaimer: true,
    squareProductUrl: 'https://tasteofgratitude.shop/s/order?add=grateful-greens',
    featured: false,
    inStock: false,
    rewardPoints: 35
  },
  {
    id: 'floral-tide',
    slug: 'floral-tide',
    name: 'Floral Tide',
    category: 'gel',
    price: 36.00,
    priceMini: 11.00,
    sizes: ['2oz Shot', '16oz Gel'],
    description: 'Hibiscus, Cranberry, Pineapple, Orange, Turmeric, Ginger, Lemon, Agave, Alkaline Water, Bee Pollen. A vibrant blend traditionally enjoyed for wellness,* rich in antioxidants & nutrients.*',
    image: 'https://127690646.cdn6.editmysite.com/uploads/1/2/7/6/127690646/BCT7OKTLSDWU3WW7P45AOHVK.jpeg',
    ingredients: ['Hibiscus', 'Cranberry', 'Pineapple', 'Orange', 'Turmeric', 'Ginger', 'Lemon', 'Agave', 'Bee Pollen'],
    benefits: ['Traditional Wellness Blend*', 'May Support Immune Wellness*', 'Traditional Comfort Blend*', 'Antioxidant Rich'],
    fdaDisclaimer: true,
    squareProductUrl: 'https://tasteofgratitude.shop/s/order?add=floral-tide',
    featured: false,
    inStock: true,
    lowStock: true,
    rewardPoints: 36
  },

  // LEMONADES - 16oz Bottles
  {
    id: 'pineapple-basil',
    slug: 'pineapple-basil',
    name: 'Pineapple Basil',
    category: 'lemonade',
    price: 11.00,
    size: '16oz',
    description: 'Pineapple Basil Lemonade: Pineapple, Basil, lemons, alkaline water, agave.',
    image: 'https://127690646.cdn6.editmysite.com/uploads/1/2/7/6/127690646/BLRQKPOBCADIZ43JPJQ6ZKQT.jpeg',
    ingredients: ['Pineapple', 'Basil', 'Lemons', 'Alkaline Water', 'Agave'],
    benefits: ['Refreshing', 'Digestive Support', 'Natural Energy'],
    squareProductUrl: 'https://tasteofgratitude.shop/s/order?add=pineapple-basil',
    featured: true,
    inStock: true,
    rewardPoints: 11
  },
  {
    id: 'apple-cranberry',
    slug: 'apple-cranberry',
    name: 'Apple Cranberry',
    category: 'lemonade',
    price: 12.00,
    size: '16oz',
    description: 'A refreshing fusion of apple, pineapple, cranberry, lime, lemon, ginger, and mineral-rich sea moss. This blend may support digestion and delivers natural energy.* Packed with antioxidants and rich mineral content.',
    image: 'https://127690646.cdn6.editmysite.com/uploads/1/2/7/6/127690646/7XDOGKFATQ3X3VFIXMU43MWH.jpeg',
    ingredients: ['Apple', 'Pineapple', 'Cranberry', 'Lime', 'Lemon', 'Ginger', 'Sea Moss'],
    benefits: ['Digestive Support', 'May Support Immune Wellness*', 'Natural Energy', 'Rich Mineral Content'],
    fdaDisclaimer: true,
    squareProductUrl: 'https://tasteofgratitude.shop/s/order?add=apple-cranberry',
    featured: true,
    inStock: true,
    lowStock: true,
    rewardPoints: 12
  },
  {
    id: 'grateful-guardian',
    slug: 'grateful-guardian',
    name: 'Grateful Guardian',
    category: 'lemonade',
    price: 11.00,
    size: '16oz',
    description: 'A tangy blend of elderberry, cranberry, apple, ginger, lemon, echinacea, sea moss, and alkaline water — crafted to may support immune wellness,* support digestion, and deliver rich mineral content in every sip.*',
    image: 'https://127690646.cdn6.editmysite.com/uploads/1/2/7/6/127690646/BXLLKEBC55LYDWKNGR46FBOC.jpeg',
    ingredients: ['Elderberry', 'Cranberry', 'Apple', 'Ginger', 'Lemon', 'Echinacea', 'Sea Moss'],
    benefits: ['May Support Immune Wellness*', 'Traditional Comfort Blend*', 'Digestive Support', 'Rich Mineral Content'],
    fdaDisclaimer: true,
    squareProductUrl: 'https://tasteofgratitude.shop/s/order?add=grateful-guardian',
    featured: true,
    inStock: true,
    rewardPoints: 11
  },
  {
    id: 'rejuvenate',
    slug: 'rejuvenate',
    name: 'Rejuvenate',
    category: 'lemonade',
    price: 11.00,
    size: '16oz',
    description: 'Grapefruit, orange, turmeric, key lime, cayenne, ginger, chia seeds, sea moss, maple, alkaline water. A refreshing blend crafted for your wellness routine.*',
    image: 'https://127690646.cdn6.editmysite.com/uploads/1/2/7/6/127690646/KE2L2V6L4STXXRBDNCG6DRX4.jpeg',
    ingredients: ['Grapefruit', 'Orange', 'Turmeric', 'Key Lime', 'Cayenne', 'Ginger', 'Chia Seeds', 'Sea Moss', 'Maple'],
    benefits: ['Refreshing Blend', 'Warming Spices', 'Traditional Comfort Blend*', 'May Support Immune Wellness*'],
    fdaDisclaimer: true,
    squareProductUrl: 'https://tasteofgratitude.shop/s/order?add=rejuvenate',
    featured: false,
    inStock: true,
    rewardPoints: 11
  },
  {
    id: 'supplemint',
    slug: 'supplemint',
    name: 'SuppleMint',
    category: 'lemonade',
    price: 11.00,
    size: '16oz',
    description: 'Mint, ginger, agave, sea moss, alkaline water. A refreshing blend that may support digestion.* Cool and invigorating.',
    image: 'https://127690646.cdn6.editmysite.com/uploads/1/2/7/6/127690646/I47GEZOG7LWKFK5THGLJVCFP.jpeg',
    ingredients: ['Mint', 'Ginger', 'Agave', 'Sea Moss', 'Alkaline Water'],
    benefits: ['Refreshing', 'Digestive Support*', 'Cool & Invigorating', 'Mineral-Rich'],
    fdaDisclaimer: true,
    squareProductUrl: 'https://tasteofgratitude.shop/s/order?add=supplemint',
    featured: false,
    inStock: true,
    rewardPoints: 11
  },
  {
    id: 'pineapple-mango',
    slug: 'pineapple-mango',
    name: 'Pineapple Mango Lemonade',
    category: 'lemonade',
    price: 11.00,
    size: '16oz',
    description: 'A tropical blend of pineapple, mango, and lemon with ginger, sea moss, agave, and alkaline water. Packed with Vitamin C, digestive enzymes, and rich mineral content, this tropical blend is crafted to support your daily wellness routine.*',
    image: 'https://127690646.cdn6.editmysite.com/uploads/1/2/7/6/127690646/UCF3MSCWPZRQKW7NFGXIKMGV.jpeg',
    ingredients: ['Pineapple', 'Mango', 'Lemon', 'Ginger', 'Sea Moss', 'Agave'],
    benefits: ['May Support Immune Wellness*', 'Digestive Support*', 'Natural Energy', 'Hydration'],
    fdaDisclaimer: true,
    squareProductUrl: 'https://tasteofgratitude.shop/s/order?add=pineapple-mango',
    featured: false,
    inStock: true,
    rewardPoints: 11
  },
  {
    id: 'kissed-by-gods',
    slug: 'kissed-by-gods',
    name: 'Kissed by Gods',
    category: 'lemonade',
    price: 11.00,
    size: '16oz',
    description: 'Basil, Chlorophyll, Ginger, Lemon, Sea Moss, Agave. A green blend crafted for hydration and natural energy, made with ingredients traditionally enjoyed for wellness.*',
    image: 'https://127690646.cdn6.editmysite.com/uploads/1/2/7/6/127690646/FCXGGWWNRAR3ROIOPDBIO6M4.jpeg',
    ingredients: ['Basil', 'Chlorophyll', 'Ginger', 'Lemon', 'Sea Moss', 'Agave'],
    benefits: ['Traditional Wellness Blend*', 'Hydration', 'Natural Energy', 'Nutrient-Rich'],
    fdaDisclaimer: true,
    squareProductUrl: 'https://tasteofgratitude.shop/s/order?add=kissed-by-gods',
    featured: false,
    inStock: true,
    rewardPoints: 11
  },
  {
    id: 'pineapple-melon',
    slug: 'pineapple-melon',
    name: 'Pineapple Melon',
    category: 'lemonade',
    price: 10.00,
    size: '16oz',
    description: 'Pineapple, yellow watermelon, ginger, lemon, sea moss. Contains compounds traditionally associated with comfort,* may support digestion, naturally hydrating.*',
    image: 'https://127690646.cdn6.editmysite.com/uploads/1/2/7/6/127690646/OX24GKXIUI4TBDNC52GQEJYH.jpeg',
    ingredients: ['Pineapple', 'Yellow Watermelon', 'Ginger', 'Lemon', 'Sea Moss'],
    benefits: ['Traditional Comfort Blend*', 'Digestive Support*', 'Hydrating'],
    fdaDisclaimer: true,
    squareProductUrl: 'https://tasteofgratitude.shop/s/order?add=pineapple-melon',
    featured: false,
    inStock: false,
    rewardPoints: 10
  },
  {
    id: 'herbal-vibe',
    slug: 'herbal-vibe',
    name: 'Herbal Vibe',
    category: 'lemonade',
    price: 12.00,
    size: '16oz',
    description: 'A bold blend featuring pineapple, apple, ginger, oregano, mint, and lemon, thoughtfully crafted to invigorate your senses. Enjoy a refreshing mix designed to energize, purify, and support your daily wellness routine.',
    image: 'https://127690646.cdn6.editmysite.com/uploads/1/2/7/6/127690646/AOJWRGGCAEM2WWMF2AZQO3CN.jpeg',
    ingredients: ['Pineapple', 'Apple', 'Ginger', 'Oregano', 'Mint', 'Lemon'],
    benefits: ['Energize', 'Purify', 'Wellness Support'],
    squareProductUrl: 'https://tasteofgratitude.shop/s/order?add=herbal-vibe',
    featured: false,
    inStock: false,
    rewardPoints: 12
  },
  {
    id: 'strawberry-rhubarb',
    slug: 'strawberry-rhubarb',
    name: 'Strawberry Rhubarb',
    category: 'lemonade',
    price: 10.00,
    size: '16oz',
    description: 'Strawberry Rhubarb - Sea Moss Ginger Lemonade combines refreshing fruity flavors with nutrient-rich sea moss and zesty ginger. A delicious addition to your wellness routine.*',
    image: 'https://127690646.cdn6.editmysite.com/uploads/1/2/7/6/127690646/JNDX77PLQHLNWEZBUMELFA2P.jpeg',
    ingredients: ['Strawberry', 'Rhubarb', 'Sea Moss', 'Ginger', 'Lemon'],
    benefits: ['May Support Immune Wellness*', 'Wellness Routine', 'Refreshing'],
    fdaDisclaimer: true,
    squareProductUrl: 'https://tasteofgratitude.shop/s/order?add=strawberry-rhubarb',
    featured: false,
    inStock: false,
    rewardPoints: 10
  },
  {
    id: 'strawberry-bliss',
    slug: 'strawberry-bliss',
    name: 'Strawberry Bliss',
    category: 'lemonade',
    price: 10.00,
    size: '16oz',
    description: 'Refreshing blend of tangy strawberry lemonade combined with nutrient-rich sea moss and invigorating ginger. Perfect for hydration and your daily wellness routine.*',
    fdaDisclaimer: true,
    image: 'https://127690646.cdn6.editmysite.com/uploads/1/2/7/6/127690646/JNDX77PLQHLNWEZBUMELFA2P.jpeg',
    ingredients: ['Strawberry', 'Lemon', 'Sea Moss', 'Ginger'],
    benefits: ['Hydration', 'Wellness Support', 'Refreshing'],
    squareProductUrl: 'https://tasteofgratitude.shop/s/order?add=strawberry-bliss',
    featured: false,
    inStock: false,
    rewardPoints: 10
  },

  // WELLNESS SHOTS - 2oz
  {
    id: 'gratitude-defense',
    slug: 'gratitude-defense',
    name: 'Gratitude Defense',
    category: 'shot',
    price: 5.00,
    size: '2oz',
    description: 'Elderberry, Cranberry, Apple, Ginger, Lemon, Echinacea, Sea Moss. May support immune wellness,* digestive support, rich mineral content.',
    image: 'https://127690646.cdn6.editmysite.com/uploads/1/2/7/6/127690646/7G2QSRNEWAACVG3DXL27W7KO.jpeg',
    ingredients: ['Elderberry', 'Cranberry', 'Apple', 'Ginger', 'Lemon', 'Echinacea', 'Sea Moss'],
    benefits: ['May Support Immune Wellness*', 'Digestive Support', 'Rich Mineral Content'],
    fdaDisclaimer: true,
    squareProductUrl: 'https://tasteofgratitude.shop/s/order?add=gratitude-defense',
    featured: true,
    inStock: true,
    rewardPoints: 5
  },
  {
    id: 'spicy-bloom',
    slug: 'spicy-bloom',
    name: 'Spicy Bloom',
    category: 'shot',
    price: 5.00,
    size: '2oz',
    description: 'Hibiscus, Pineapple, Orange, Cranberry, Lemon, Jalapeño, Sea Moss, Agave, Alkaline Water.',
    image: 'https://127690646.cdn6.editmysite.com/uploads/1/2/7/6/127690646/EJ3LK4ECIAME3LAUHBIBLZ2L.jpeg',
    ingredients: ['Hibiscus', 'Pineapple', 'Orange', 'Cranberry', 'Lemon', 'Jalapeño', 'Sea Moss', 'Agave'],
    benefits: ['Warming Spices', 'Invigorating', 'Spicy Kick'],
    fdaDisclaimer: true,
    squareProductUrl: 'https://tasteofgratitude.shop/s/order?add=spicy-bloom',
    featured: true,
    inStock: true,
    rewardPoints: 5
  }
];

// Helper functions
export const getProductBySlug = (slug) => {
  return PRODUCTS.find(p => p.slug === slug);
};

export const getProductsByCategory = (category) => {
  return PRODUCTS.filter(p => p.category === category);
};

export const getFeaturedProducts = () => {
  return PRODUCTS.filter(p => p.featured);
};

export const getInStockProducts = () => {
  return PRODUCTS.filter(p => p.inStock !== false);
};

// Export for backward compatibility
export default PRODUCTS;
