import {getTursoConnection} from '../db/turso';
import {DEFAULT_REWARDS,TIER_ORDER} from './core';
const select='SELECT id,name,description,credits_cost,reward_type,reward_value,minimum_order_cents,tier_requirement,active,expires_days,redemption_count,created_at,updated_at FROM reward_catalog';
const map=(r)=>({_id:r.id,id:r.id,name:r.name,description:r.description,creditsCost:Number(r.credits_cost),rewardType:r.reward_type,rewardValue:Number(r.reward_value),minimumOrder:Number(r.minimum_order_cents),tierRequirement:r.tier_requirement,active:Boolean(r.active),expiresDays:Number(r.expires_days),redemptionCount:Number(r.redemption_count),createdAt:new Date(r.created_at),updatedAt:new Date(r.updated_at)});
export function validateReward(reward){const errors=[];if(!reward.name)errors.push('Name is required');if(!reward.description)errors.push('Description is required');if(!reward.creditsCost||reward.creditsCost<1)errors.push('Credits cost must be at least 1');if(!reward.rewardType)errors.push('Reward type is required');if(reward.rewardValue<0)errors.push('Reward value cannot be negative');if(reward.minimumOrder<0)errors.push('Minimum order cannot be negative');const types=['discount_fixed','discount_percent','free_shipping','free_product','experience'];if(!types.includes(reward.rewardType))errors.push(`Invalid reward type. Must be one of: ${types.join(', ')}`);if(reward.tierRequirement&&!TIER_ORDER.includes(reward.tierRequirement))errors.push(`Invalid tier requirement. Must be one of: ${TIER_ORDER.join(', ')}`);return{valid:errors.length===0,errors}}
async function insert(tx,reward){const now=new Date().toISOString();return tx.run(`INSERT INTO reward_catalog(id,name,description,credits_cost,reward_type,reward_value,minimum_order_cents,tier_requirement,active,expires_days,redemption_count,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`,reward.id,reward.name,reward.description,reward.creditsCost,reward.rewardType,reward.rewardValue,reward.minimumOrder??0,reward.tierRequirement??null,reward.active===false?0:1,reward.expiresDays??30,reward.redemptionCount??0,now,now)}
export async function initializeDefaultRewards(){const db=getTursoConnection();if(Number((await db.get('SELECT count(*) AS count FROM reward_catalog'))?.count??0)>0)return{alreadyInitialized:true};await db.transactionAsync(async tx=>{for(const reward of DEFAULT_REWARDS)await insert(tx,reward)});return{initialized:true,count:DEFAULT_REWARDS.length}}
export async function getActiveRewards(options={}){const include=options.includeInactive===true;let rows=await getTursoConnection().all(`${select}${include?'':' WHERE active=1'} ORDER BY credits_cost`);let rewards=rows.map(map);if(options.tier){const tier=TIER_ORDER.indexOf(options.tier);rewards=rewards.filter(r=>!r.tierRequirement||tier>=TIER_ORDER.indexOf(r.tierRequirement))}return rewards}
export async function getRewardById(id){const row=await getTursoConnection().get(`${select} WHERE id=? LIMIT 1`,id);return row?map(row):null}
export async function createReward(reward){const validation=validateReward(reward);if(!validation.valid)return{success:false,errors:validation.errors};try{await insert(getTursoConnection(),{...reward,redemptionCount:0,active:true});return{success:true,reward:await getRewardById(reward.id)}}catch(error){if(String(error?.message||'').toLowerCase().includes('unique'))return{success:false,error:'Reward with this ID already exists'};throw error}}
export async function updateReward(id,updates){const allowed={name:'name',description:'description',creditsCost:'credits_cost',rewardType:'reward_type',rewardValue:'reward_value',minimumOrder:'minimum_order_cents',tierRequirement:'tier_requirement',active:'active',expiresDays:'expires_days'},sets=['updated_at=?'],values=[new Date().toISOString()];for(const[key,column]of Object.entries(allowed)){if(updates[key]===undefined)continue;sets.push(`${column}=?`);values.push(typeof updates[key]==='boolean'?(updates[key]?1:0):updates[key])}const result=await getTursoConnection().run(`UPDATE reward_catalog SET ${sets.join(',')} WHERE id=?`,...values,id);return Number(result.rowsAffected)===1?{success:true,reward:await getRewardById(id)}:{success:false,error:'Reward not found'}}
export async function toggleRewardStatus(id){const result=await getTursoConnection().run('UPDATE reward_catalog SET active=CASE active WHEN 1 THEN 0 ELSE 1 END,updated_at=? WHERE id=?',new Date().toISOString(),id);return Number(result.rowsAffected)===1?{success:true,reward:await getRewardById(id)}:{success:false,error:'Reward not found'}}
export async function deleteReward(id){return Number((await getTursoConnection().run('DELETE FROM reward_catalog WHERE id=?',id)).rowsAffected)===1?{success:true}:{success:false,error:'Reward not found'}}
export async function incrementRedemptionCount(id){await getTursoConnection().run('UPDATE reward_catalog SET redemption_count=redemption_count+1,updated_at=? WHERE id=?',new Date().toISOString(),id)}
export async function getRewardAnalytics(){const db=getTursoConnection(),overview=await db.get('SELECT count(*) AS totalRewards,sum(active) AS activeRewards,sum(redemption_count) AS totalRedemptions,avg(credits_cost) AS avgCost FROM reward_catalog'),rows=await db.all('SELECT reward_type AS type,count(*) AS count,sum(redemption_count) AS totalRedemptions FROM reward_catalog GROUP BY reward_type');return{overview:overview??{},byType:Object.fromEntries(rows.map(r=>[r.type,{count:Number(r.count),totalRedemptions:Number(r.totalRedemptions)}]))}}
export async function getPopularRewards(limit=5){return(await getTursoConnection().all(`${select} WHERE active=1 ORDER BY redemption_count DESC LIMIT ?`,Math.max(1,Math.min(50,Number(limit)||5)))).map(map)}
export async function getAffordableRewards(balance,tier){const rewards=await getActiveRewards({tier});return{affordable:rewards.filter(r=>r.creditsCost<=balance),upcoming:rewards.filter(r=>r.creditsCost>balance).sort((a,b)=>a.creditsCost-b.creditsCost).slice(0,3)}}
export default{initializeDefaultRewards,getActiveRewards,getRewardById,validateReward,createReward,updateReward,toggleRewardStatus,deleteReward,incrementRedemptionCount,getRewardAnalytics,getPopularRewards,getAffordableRewards};
