import { randomUUID } from 'node:crypto';
import { getTursoConnection } from '../db/turso';
import { calculatePurchaseCredits, calculateExpiration, generateCouponCode, validateRedemption, checkTierUpgrade } from './core';
import { getAccount } from './accounts';

const iso=(value)=>value instanceof Date?value.toISOString():new Date(value).toISOString();
const parse=(value)=>{if(!value)return{};try{return JSON.parse(value)}catch{return{}}};
const source=(type,details={})=>({type,...details});
function mapTransaction(row){return row?{_id:String(row.id),customerId:row.customer_id,type:row.event_type,credits:Number(row.delta_points),source:parse(row.metadata_json),createdAt:new Date(row.created_at)}:null}

async function accountRow(customerId,db=getTursoConnection()){return db.get('SELECT * FROM reward_accounts WHERE customer_id=? LIMIT 1',customerId)}
async function insertLedger(tx,{id=randomUUID(),accountId,delta,type,eventKey,createdAt=new Date(),metadata={}}){await tx.run('INSERT INTO reward_transactions(id,reward_account_id,delta_points,event_type,source_event_id,created_at,metadata_json) VALUES(?,?,?,?,?,?,?)',id,accountId,delta,type,eventKey,iso(createdAt),JSON.stringify(metadata));return id}
async function changeBalance(tx,customerId,delta,now=new Date()){
  const expiration=calculateExpiration(now).toISOString();
  const result=await tx.run(`UPDATE reward_accounts SET points=points+?,lifetime_earned=lifetime_earned+CASE WHEN ?>0 THEN ? ELSE 0 END,lifetime_redeemed=lifetime_redeemed+CASE WHEN ?<0 THEN -? ELSE 0 END,last_earned_at=CASE WHEN ?>0 THEN ? ELSE last_earned_at END,last_redeemed_at=CASE WHEN ?<0 THEN ? ELSE last_redeemed_at END,expires_at=?,updated_at=? WHERE customer_id=? AND points+?>=0`,delta,delta,delta,delta,delta,delta,now.toISOString(),delta,now.toISOString(),expiration,now.toISOString(),customerId,delta);
  if(Number(result.rowsAffected)!==1)throw new Error('Reward account not found or insufficient balance');
}

export async function earnFromPurchase({customerId,orderId,orderTotal,tier,isFirstPurchase=false,isPreorder=false,metadata={}}){
  const db=getTursoConnection(),eventKey=`purchase:${customerId}:${orderId}`;
  const existing=await db.get(`SELECT t.*,a.customer_id FROM reward_transactions t JOIN reward_accounts a ON a.id=t.reward_account_id WHERE t.source_event_id=? LIMIT 1`,eventKey);
  if(existing)return{success:true,duplicate:true,transaction:mapTransaction(existing),message:'Credits already awarded for this order'};
  const credits=calculatePurchaseCredits(orderTotal,tier,{isFirstPurchase,isPreorder});if(credits<=0)return{success:true,credits:0,message:'No credits earned'};
  const account=await accountRow(customerId,db);if(!account)throw new Error('Reward account not found');
  const now=new Date(),progress={purchases:Number(account.progress_purchases)+1,spent:Number(account.progress_spent_cents)+Number(orderTotal),credits:Number(account.lifetime_earned)+credits};
  const upgrade=checkTierUpgrade(account.tier,progress);const id=randomUUID();
  await db.transactionAsync(async tx=>{await insertLedger(tx,{id,accountId:account.id,delta:credits,type:'earn',eventKey,createdAt:now,metadata:source('purchase',{orderId,metadata:{orderTotal,tier,isFirstPurchase,isPreorder,...metadata}})});await changeBalance(tx,customerId,credits,now);await tx.run('UPDATE reward_accounts SET progress_purchases=?,progress_spent_cents=?,tier=?,tier_achieved_at=CASE WHEN ? THEN ? ELSE tier_achieved_at END,updated_at=? WHERE customer_id=?',progress.purchases,progress.spent,upgrade.upgraded?upgrade.to:account.tier,upgrade.upgraded?1:0,now.toISOString(),now.toISOString(),customerId)});
  return{success:true,transaction:{_id:id,customerId,type:'earn',credits,source:source('purchase',{orderId}),createdAt:now},credits,tierUpgrade:upgrade.upgraded?upgrade:null};
}

export async function earnFromActivity({customerId,activityType,credits,description,metadata={}}){
  const eventKey=activityType==='review'?`review:${customerId}:${metadata.productId}`:activityType==='birthday'?`birthday:${customerId}:${new Date().getFullYear()}`:activityType==='referral'?`referral:${customerId}:${metadata.referredCustomerId}`:metadata.eventId?`${activityType}:${metadata.eventId}`:`${activityType}:${randomUUID()}`;
  const db=getTursoConnection(),existing=await db.get('SELECT id FROM reward_transactions WHERE source_event_id=? LIMIT 1',eventKey);
  if(existing)return activityType==='referral'?{success:true,duplicate:true,transaction:{_id:existing.id},credits:0}:{success:false,error:activityType==='review'?'Already reviewed this product':activityType==='birthday'?'Birthday bonus already awarded this year':'Activity already credited',transaction:{_id:existing.id}};
  const account=await accountRow(customerId,db);if(!account)throw new Error('Reward account not found');const id=randomUUID(),now=new Date();
  await db.transactionAsync(async tx=>{await insertLedger(tx,{id,accountId:account.id,delta:Number(credits),type:'earn',eventKey,createdAt:now,metadata:source(activityType,{description,metadata})});await changeBalance(tx,customerId,Number(credits),now)});
  return{success:true,transaction:{_id:id,customerId,type:'earn',credits,source:source(activityType,{metadata}),description,createdAt:now},credits};
}

export async function redeemCredits({customerId,rewardId,rewardConfig,cartTotal=0}){
  const account=await getAccount(customerId);if(!account)return{success:false,error:'Account not found'};
  const validation=validateRedemption(account,rewardConfig,cartTotal);if(!validation.valid)return{success:false,errors:validation.errors};
  const db=getTursoConnection(),credits=Number(rewardConfig.creditsCost),couponCode=generateCouponCode(account.tier.current),now=new Date(),expiresAt=new Date(now);expiresAt.setDate(expiresAt.getDate()+(rewardConfig.expiresDays||30));const transactionId=randomUUID(),redemptionId=randomUUID();
  await db.transactionAsync(async tx=>{await insertLedger(tx,{id:transactionId,accountId:String(account._id),delta:-credits,type:'redeem',eventKey:`redemption:${redemptionId}`,createdAt:now,metadata:source('reward_redemption',{rewardId,couponCode,rewardType:rewardConfig.rewardType,rewardValue:rewardConfig.rewardValue})});await tx.run(`INSERT INTO reward_redemptions(id,reward_account_id,customer_id,reward_id,coupon_code,credits_cost,reward_type,reward_value_json,minimum_order_cents,applied,expires_at,created_at) VALUES(?,?,?,?,?,?,?,?,?,0,?,?)`,redemptionId,String(account._id),customerId,rewardId,couponCode,credits,rewardConfig.rewardType,JSON.stringify(rewardConfig.rewardValue??null),rewardConfig.minimumOrder??null,expiresAt.toISOString(),now.toISOString());await changeBalance(tx,customerId,-credits,now)});
  return{success:true,transaction:{_id:transactionId},redemption:{couponCode,expiresAt,rewardName:rewardConfig.name},creditsSpent:credits,newBalance:account.credits.balance-credits};
}

export async function applyCoupon({couponCode,customerId,orderId}){const db=getTursoConnection(),redemption=await db.get('SELECT * FROM reward_redemptions WHERE coupon_code=? AND customer_id=? LIMIT 1',couponCode,customerId);if(!redemption)return{success:false,error:'Invalid coupon code'};if(Number(redemption.applied))return{success:false,error:'Coupon already used'};if(Date.now()>Date.parse(redemption.expires_at))return{success:false,error:'Coupon expired'};const result=await db.run('UPDATE reward_redemptions SET applied=1,applied_at=?,order_id=? WHERE id=? AND applied=0',new Date().toISOString(),orderId,redemption.id);if(Number(result.rowsAffected)!==1)return{success:false,error:'Coupon already used'};return{success:true,redemption:{rewardType:redemption.reward_type,rewardValue:parse(redemption.reward_value_json),minimumOrder:redemption.minimum_order_cents}}}
export async function getTransactionHistory(customerId,{limit=50,skip=0,type=null}={}){const db=getTursoConnection(),values=[customerId];let filter='';if(type){filter=' AND t.event_type=?';values.push(type)}values.push(Math.min(Math.max(1,Number(limit)),200),Math.max(0,Number(skip)));const rows=await db.all(`SELECT t.*,a.customer_id FROM reward_transactions t JOIN reward_accounts a ON a.id=t.reward_account_id WHERE a.customer_id=?${filter} ORDER BY t.created_at DESC LIMIT ? OFFSET ?`,...values);return rows.map(mapTransaction)}
export async function getRedemptionHistory(customerId){return (await getTursoConnection().all('SELECT * FROM reward_redemptions WHERE customer_id=? ORDER BY created_at DESC',customerId)).map(row=>({...row,_id:String(row.id),customerId:row.customer_id,couponCode:row.coupon_code,creditsCost:Number(row.credits_cost),rewardType:row.reward_type,rewardValue:parse(row.reward_value_json),minimumOrder:row.minimum_order_cents,applied:Boolean(row.applied),appliedAt:row.applied_at?new Date(row.applied_at):null,orderId:row.order_id,expiresAt:new Date(row.expires_at),createdAt:new Date(row.created_at)}))}

export async function expireOldCredits(batchSize=1000){const db=getTursoConnection(),now=new Date(),rows=await db.all(`SELECT a.id,a.customer_id,a.points FROM reward_accounts a WHERE a.expires_at<=? AND a.points>0 ORDER BY a.expires_at LIMIT ?`,now.toISOString(),Math.min(Math.max(1,batchSize),1000));const results={processed:0,creditsExpired:0,errors:[]};for(const row of rows){try{await db.transactionAsync(async tx=>{const key=`expiration:${row.id}:${iso(now).slice(0,10)}`;const claim=await tx.run('INSERT OR IGNORE INTO reward_transactions(id,reward_account_id,delta_points,event_type,source_event_id,created_at,metadata_json) VALUES(?,?,?,?,?,?,?)',randomUUID(),row.id,-Number(row.points),'expire',key,now.toISOString(),JSON.stringify(source('expiration')));if(Number(claim.rowsAffected)!==1)return;await changeBalance(tx,row.customer_id,-Number(row.points),now)});results.processed++;results.creditsExpired+=Number(row.points)}catch(error){results.errors.push({transactionId:String(row.id),error:error.message})}}return results}
export async function reverseCreditsForRefund(orderId){const db=getTursoConnection(),original=await db.get(`SELECT t.*,a.customer_id FROM reward_transactions t JOIN reward_accounts a ON a.id=t.reward_account_id WHERE t.source_event_id LIKE ? AND t.event_type='earn' LIMIT 1`,`purchase:%:${orderId}`);if(!original)return{success:false,error:'No credits found for this order'};const key=`refund:${original.id}`;if(await db.get('SELECT id FROM reward_transactions WHERE source_event_id=? LIMIT 1',key))return{success:false,error:'Credits already reversed'};await db.transactionAsync(async tx=>{await insertLedger(tx,{accountId:original.reward_account_id,delta:-Number(original.delta_points),type:'adjust',eventKey:key,metadata:source('refund_reversal',{originalTransactionId:String(original.id),orderId})});await changeBalance(tx,original.customer_id,-Number(original.delta_points))});return{success:true,creditsReversed:Number(original.delta_points)}}
export async function manualAdjustment({customerId,credits,reason,adminId}){const db=getTursoConnection(),account=await accountRow(customerId,db);if(!account)throw new Error('Reward account not found');const id=randomUUID(),now=new Date();await db.transactionAsync(async tx=>{await insertLedger(tx,{id,accountId:account.id,delta:Number(credits),type:'adjust',eventKey:`manual:${id}`,createdAt:now,metadata:source('manual_adjustment',{reason,adminId})});await changeBalance(tx,customerId,Number(credits),now)});return{success:true,transaction:{_id:id,customerId,type:'adjust',credits,source:source('manual_adjustment',{metadata:{reason,adminId}}),description:`Manual adjustment: ${reason}`,createdAt:now}}}
export async function getTransactionAnalytics(days=30){const since=new Date(Date.now()-days*86400000).toISOString(),rows=await getTursoConnection().all('SELECT event_type,count(*) count,coalesce(sum(delta_points),0) total FROM reward_transactions WHERE created_at>=? GROUP BY event_type',since),summary={};for(const row of rows)summary[row.event_type]={count:Number(row.count),totalCredits:Number(row.total)};return{period:`${days} days`,since,summary}}
export default{earnFromPurchase,earnFromActivity,redeemCredits,applyCoupon,getTransactionHistory,getRedemptionHistory,expireOldCredits,reverseCreditsForRefund,manualAdjustment,getTransactionAnalytics};
